frontend/app/contacts/__init__.py
from flask import Blueprint

bp = Blueprint('contacts', __name__)


from app.contacts import routes

frontend/app/contacts/routes.py
from flask import render_template
from app.contacts import bp
from flask import current_app


@bp.route('/contacts/<asn>/<ix>')
def contacts(asn,ix):
    cadastro_url = current_app.config.get('CADASTRO_API_URL')
    all_asns_data, ix_atual, ix_atual_code = api_cadastro.get_asns_and_ix(cadastro_url, None, None)
    return render_template('/contacts/contacts.html',
                           all_asns_data=all_asns_data,
                           ix_atual=ix_atual,
                           asn_route=asn,
                           ix_route=ix,
                           cadastro_url=cadastro_url,
                           )

@bp.route('/contacts')
def contacts_mock():
    cadastro_url = current_app.config.get('CADASTRO_API_URL')
    all_asns_data, ix_atual, ix_atual_code = api_cadastro.get_asns_and_ix(cadastro_url, None, None)
    return render_template('/contacts/contacts-mock.html',
                           cadastro_url=cadastro_url,
                           all_asns_data=all_asns_data,
                           ix_atual=ix_atual,
                           )

frontend/app/ecommerce/__init__.py
from flask import Blueprint

bp = Blueprint('ecommerce', __name__)

from app.ecommerce import routes

frontend/app/ecommerce/routes.py
from flask import render_template, session, request
from app.ecommerce import bp
from flask import current_app
from app.authentication import functions as auth
from app.books import api as books_api
import ast, random

@bp.route('/')
def index():
  ##backend_url = current_app.config.get('BACKEND_API_URL')
  ##books_url = backend_url + 'books/all'
  #params = {
   #'method': 'GET',
   #'url': books_url,
  #}
  #response = books_api.api_books(params)
  #our_library = ast.literal_eval(response)
  #if len(our_library) >= 3:
        #random_books = random.sample(our_library, 3)
  return render_template('/ecommerce/index.html', page="index")

@bp.route('/about')
def about():
  return render_template('/ecommerce/about.html', page="about")

@bp.route('/cart')
def cart():
  return render_template('/ecommerce/cart.html')

@bp.route('/checkout')
def checkout():
  return render_template('/ecommerce/checkout.html')

@bp.route('/contact')
def contact():
  return render_template('/ecommerce/contact.html', page="contact")

@bp.route('/summary')
def summary():
  return render_template('/ecommerce/summary.html', page="summary")

@bp.route('/shop')
def shop():
  return render_template('/ecommerce/shop.html', page="shop")

@bp.route('/search')
def search():
  query = request.args.get('query')
  backend_url = current_app.config.get('BACKEND_API_URL')
  search_url = backend_url + 'books/search?query=' + query
  params = {
    'method': 'GET',
    'url': search_url,
    'token': session['token'] if 'token' in session else None
  }
  response = books_api.api_books(params)
  if type(response) != dict:
<<<<<<< HEAD
    response = ast.literal_eval(response)
    
=======
    response = eval(response)
    
  # if 'error' in response:
  #   flash(response['error'], 'danger')
>>>>>>> backend-joao
  return render_template('/ecommerce/search.html', page="shop", books=response)

@bp.route('/single-news')
def single_news():
  return render_template('/ecommerce/single-news.html')

@bp.route('/book/<book_id>')
def book(book_id):
  backend_url = current_app.config.get('BACKEND_API_URL')
  book_url = backend_url + f'books/{book_id}' 
  params = {
    'method': 'GET',
    'url': book_url,
    'token': session['token'] if 'token' in session else None
  }
  response = books_api.api_books(params)
  if type(response) != dict:
    response = eval(response)    
  return render_template('/ecommerce/product.html', book=response)

@bp.route('/error-page')
def error_page():
  return render_template('/ecommerce/error-page.html')

frontend/app/templates/ecommerce/cart.html
{% extends "base-ecommerce.html" %}

{% block title %}Bookshifter - Carrinho{% endblock title %}

	{% block content %}
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<h2 style="color: #fff;">Vamos finalizar sua compra?</h2>
						<!-- <h1>Cart</h1> -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- cart -->
	<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>
									<th class="product-image">Product Image</th>
									<th class="product-name">Name</th>
									<th class="product-price">Price</th>
									<th class="product-quantity">Quantity</th>
									<th class="product-total">Total</th>
								</tr>
							</thead>
							<tbody>
								<tr class="table-body-row">
									<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
									<td class="product-image"><img src="assets/img/products/product-img-1.jpg" alt=""></td>
									<td class="product-name">Strawberry</td>
									<td class="product-price">$85</td>
									<td class="product-quantity"><input type="number" placeholder="0"></td>
									<td class="product-total">1</td>
								</tr>
								<tr class="table-body-row">
									<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
									<td class="product-image"><img src="assets/img/products/product-img-2.jpg" alt=""></td>
									<td class="product-name">Berry</td>
									<td class="product-price">$70</td>
									<td class="product-quantity"><input type="number" placeholder="0"></td>
									<td class="product-total">1</td>
								</tr>
								<tr class="table-body-row">
									<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
									<td class="product-image"><img src="assets/img/products/product-img-3.jpg" alt=""></td>
									<td class="product-name">Lemon</td>
									<td class="product-price">$35</td>
									<td class="product-quantity"><input type="number" placeholder="0"></td>
									<td class="product-total">1</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>Total</th>
									<th>Price</th>
								</tr>
							</thead>
							<tbody>
								<tr class="total-data">
									<td><strong>Subtotal: </strong></td>
									<td>$500</td>
								</tr>
								<tr class="total-data">
									<td><strong>Shipping: </strong></td>
									<td>$45</td>
								</tr>
								<tr class="total-data">
									<td><strong>Total: </strong></td>
									<td>$545</td>
								</tr>
							</tbody>
						</table>
						<div class="cart-buttons">
							<a href="cart.html" class="boxed-btn">Update Cart</a>
							<a href="checkout.html" class="boxed-btn black">Check Out</a>
						</div>
					</div>

					<div class="coupon-section">
						<h3>Apply Coupon</h3>
						<div class="coupon-form-wrap">
							<form action="index.html">
								<p><input type="text" placeholder="Coupon"></p>
								<p><input type="submit" value="Apply"></p>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end cart -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="assets/img/company-logos/1.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/2.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/3.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/4.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/5.png" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

	{% endblock content %}

frontend/app/templates/ecommerce/error-page.html
{% extends "base-ecommerce.html" %}

{% block title %}Bookshifter - Erro{% endblock title %}

	{% block content %}
		<!-- breadcrumb-section -->
		<div class="breadcrumb-section breadcrumb-bg">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 offset-lg-2 text-center">
						<div class="breadcrumb-text">
							<p>Fresh adn Organic</p>
							<h1>404 - Not Found</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end breadcrumb section -->
		<!-- error section -->
		<div class="full-height-section error-section">
			<div class="full-height-tablecell">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 offset-lg-2 text-center">
							<div class="error-text">
								<i class="far fa-sad-cry"></i>
								<h1>Oops! Not Found.</h1>
								<p>The page you requested for is not found.</p>
								<a href="index.html" class="boxed-btn">Back to Home</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end error section -->
		{% endblock content %}

frontend/app/templates/ecommerce/index.html
	{% extends "base-ecommerce.html" %}

	{% block title %}Bookshifter{% endblock title %}

	{% block content %}

	<!-- hero area -->
	<div class="hero-area hero-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="hero-text">
						<div class="hero-text-tablecell">
							<p class="subtitle">Bookshifter</p>
							<!-- <h1>Descubra Tesouros Literários em Nosso Sebo Virtual!</h1> -->
							<h1>Onde os livros encontram <br>novos leitores</h1>
							<!-- 
								<div class="hero-btns">
									<a href="{{url_for('ecommerce.shop')}}" class="boxed-btn">Ver mais</a>
									<a href="contact.html" class="bordered-btn">Contato</a>
								</div>
							-->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end hero area -->

	<!-- features list section -->
	<div class="list-section pt-80 pb-80">
		<div class="container">

			<div class="row">
				<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
					<div class="list-box d-flex align-items-center">
						<div class="list-icon">
							<i class="fas fa-map-marker-alt"></i>
						</div>
						<div class="content">
							<h3>Locais de retirada</h3>
							<p>Confira o local das Fatecs</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
					<div class="list-box d-flex align-items-center">
						<div class="list-icon">
							<i class="fas fa-phone-volume"></i>
						</div>
						<div class="content">
							<h3>Suporte técnico</h3>
							<p>Dias úteis das 9h às 16h</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="list-box d-flex justify-content-start align-items-center">
						<div class="list-icon">
							<i class="far fa-handshake"></i>
						</div>
						<div class="content">
							<h3>Doe mais</h3>
							<p>Incentive a leitura!</p>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	<!-- end features list section -->

	<!-- product section -->
	<div class="product-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<a href="http://localhost:8000/shop"><h3><span class="orange-text">Nossa</span> Biblioteca</h3></a>
						<p>Descubra Tesouros Literários em Nosso Sebo Virtual!</p>
						<!--<i class="fas fa-shopping-cart"></i>-->
						<a href="http://localhost:8000/shop" class="cart-btn mt-3">Ver Livros</a>
					</div>
				</div>
			</div>

			<div class="row">
				{% for book in our_library %}
					<div class="col-lg-4 col-md-6 text-center">
						<div class="single-product-item">
							<div class="product-image">
								<a href="{{url_for('ecommerce.book',  book_id=book.id)}}"><img src="{{book.mediumCoverUrl}}" ></a>
							</div>
							<h3 class="card-title" style="height: 50px;">{{book.title}}</h3>
							<div class="description-container">
								<p class="description">{{book.description}}</p>
							</div>
							<br>
							<a href="{{url_for('ecommerce.cart')}}" class="cart-btn"><i class="fas fa-shopping-cart"></i>Adicionar ao carrinho</a>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<!-- end product section -->

	

	<!-- testimonail-section -->
	<!--<div class="testimonail-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1 text-center">
					<div class="testimonial-sliders">
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="{{url_for('static', filename='img/avaters/avatar1.png')}}" alt="">
							</div>
							<div class="client-meta">
								<h3>Eduardo Alves <span>Leitor assíduo</span></h3>
								<p class="testimonial-body">
									" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Esse hic, commodi magnam reprehenderit totam sapiente nam perspiciatis aperiam, quidem porro minus quo molestiae expedita? Dolores, inventore. Asperiores dolor illum temporibus. "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="{{url_for('static', filename='img/avaters/avatar2.png')}}" alt="">
							</div>
							<div class="client-meta">
								<h3>Flávio Kawan <span>Leitor assíduo</span></h3>
								<p class="testimonial-body">
									" Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam excepturi veritatis voluptatem libero nulla maiores. Incidunt ea illum nemo nam. Doloremque necessitatibus ad numquam labore laudantium quisquam earum tempore tenetur. "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="{{url_for('static', filename='img/avaters/avatar3.png')}}" alt="">
							</div>
							<div class="client-meta">
								<h3>Gustavo Oliveira <span>Filantropo milionário</span></h3>
								<p class="testimonial-body">
									" Lorem, ipsum dolor sit amet consectetur adipisicing elit. Inventore, veritatis odio aliquam perspiciatis, error expedita labore esse quam, facere tempora quas enim. Dignissimos dolorem omnis doloribus? Hic dolor obcaecati cumque. "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>-->
	<!-- end testimonail-section -->
	
	
	<!-- shop banner -->
	<section class="shop-banner">
    	<div class="container">
        	<h3>Há mais livros para doação em Novembro! <br> com <span class="orange-text">Confira...</span></h3>
        </div>
    </section>
	<!-- end shop banner -->
	
	<!-- latest news -->
	<!--<div class="latest-news pt-150 pb-150">
		<div class="container">

			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						<h3><span class="orange-text">Resumos</span> literários</h3>
						<p>Acompanhe a trajetória de seus personagens preferidos de forma resumida!</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4 col-md-m6">
					<div class="single-latest-news">
						<a href="{{url_for('ecommerce.single_news')}}"><div class="latest-news-bg news-bg-4"></div></a>
						<div class="news-text-box">
							<h3><a href="{{url_for('ecommerce.single_news')}}">You will vainly look for fruit on it in autumn.</a></h3>
							<p class="blog-meta">
								<span class="author"><i class="fas fa-user"></i> Admin</span>
								<span class="date"><i class="fas fa-calendar"></i> 27 December, 2019</span>
							</p>
							<p class="excerpt">Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi. Praesent vitae mattis nunc, egestas viverra eros.</p>
							<a href="{{url_for('ecommerce.single_news')}}" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-latest-news">
						<a href="{{url_for('ecommerce.single_news')}}"><div class="latest-news-bg news-bg-2"></div></a>
						<div class="news-text-box">
							<h3><a href="{{url_for('ecommerce.single_news')}}">A man's worth has its season, like tomato.</a></h3>
							<p class="blog-meta">
								<span class="author"><i class="fas fa-user"></i> Admin</span>
								<span class="date"><i class="fas fa-calendar"></i> 27 December, 2019</span>
							</p>
							<p class="excerpt">Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi. Praesent vitae mattis nunc, egestas viverra eros.</p>
							<a href="{{url_for('ecommerce.single_news')}}" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 offset-md-3 offset-lg-0">
					<div class="single-latest-news">
						<a href="{{url_for('ecommerce.single_news')}}"><div class="latest-news-bg news-bg-3"></div></a>
						<div class="news-text-box">
							<h3><a href="{{url_for('ecommerce.single_news')}}">Good thoughts bear good fresh juicy fruit.</a></h3>
							<p class="blog-meta">
								<span class="author"><i class="fas fa-user"></i> Admin</span>
								<span class="date"><i class="fas fa-calendar"></i> 27 December, 2019</span>
							</p>
							<p class="excerpt">Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi. Praesent vitae mattis nunc, egestas viverra eros.</p>
							<a href="{{url_for('ecommerce.single_news')}}" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 text-center">
					<a href="{{url_for('ecommerce.summary')}}" class="boxed-btn">Mais resumos</a>
				</div>
			</div>
		</div>-->
		<!-- zap - zap -->

		<!-- Seção em Destaque -->
	<div style="box-shadow: none" class="feature-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="featured-text">
						<h2 class="pb-3">Por que o <span class="orange-text">Bookshifter?</span></h2>
						<div class="row">
							<div class="col-lg-6 col-md-6 mb-4 mb-md-5">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-map-marker-alt"></i>
									</div>
									<div class="content">
										<h3>Localização</h3>
										<p>Localize e Verifique a rota até a Fatec disponível.</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 mb-5 mb-md-5">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-barcode"></i>
									</div>
									<div class="content">
										<h3>Melhores livros</h3>
										<p>Adição de livros facilitadas através de seu ISBN (código do livro).</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 mb-5 mb-md-5">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-home"></i>
									</div>
									<div class="content">
										<h3>Colabore com a leitura</h3>
										<p>Abra espaço em sua casa e transforme a vida do próximo!</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fab fa-whatsapp"></i>
									</div>
									<div class="content">
										<h3>Contato</h3>
										<p>Suporte via WhatsApp persolizado e eficiente!</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Fim da Seção em Destaque -->
		
	<div class="buttonzap">
		<a id="btn-zap" href='https://api.whatsapp.com/send?phone=5511986592453&text=Olá,%20você%20poderia%20me%20orientar%20com%20o%20uso%20do%20BookShifter?' class="icon" target='_blank'>
		  <i class="fab fa-whatsapp"></i>
		</a>
	</div>
	</div>
	
	<!-- end latest news -->
	{% endblock %}
	

frontend/app/templates/ecommerce/search.html
{% extends "base-ecommerce.html" %}

{% block title %}Bookshifter - Buscar{% endblock title %}

	{% block content %}
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Sua Próxima Aventura Literária Começa Aqui.</p>
						<h1>Biblioteca Virtual</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- products -->
	<div class="product-section mt-150 mb-150">
		<div class="container">

<<<<<<< HEAD
			<h1 class="text-center">{{books|length}} {% if books|length > 1 %}resultados encontrados{% else %}resultado encontrado{% endif %}</h1>
			<br><br><br>
			<!-- 
				<div class="row">
					<div class="col-md-12">
						<div class="product-filters">
							<ul>
								<li class="active" data-filter="*">All</li>
								<li data-filter=".acao">Ação</li>
								<li data-filter=".romance">Romance</li>
								<li data-filter=".terror">Terror</li>
								<li data-filter=".comedia">Comédia</li>
								<li data-filter=".tensao">Tensão</li>
								<li data-filter=".superacao">Superação</li>
							</ul>
						</div>
					</div>
				</div>
			-->

			{% if not books %}
			<div class="text-center">
                <h2>Não há livros com esse título.</h2>
                <br>
                <img src="{{ url_for('static', filename= 'img/media/no-books.png') }}" style="max-width:20%;">
                <br><br><br>
                <h3>Busque outros livros!</h3>
            </div>
			{% elif 'error' in books %}
			<div class="text-center">
				<h1>Erro ao buscar livros!</h3>
				<br>
				<img src="{{ url_for('static', filename= 'img/media/no-books.png') }}" style="max-width:20%;">
				<br><br><br>
				<h3>Tente novamente mais tarde!</h3>
			</div>
			
			{% else %}
				<div class="row product-lists">
					{% for book in books %}
					<div class="col-lg-4 col-md-4 text-center">
						<div class="single-product-item">
							<div class="product-image">
								<a href="{{url_for('ecommerce.book', book_id=book.id)}}">
									<img src="{{book.mediumCoverUrl}}" style="object-fit: contain;">
								</a>
							</div>
=======
			<div class="row">
                <div class="col-md-12">
                    <div class="product-filters">
                        <ul>
                            <li class="active" data-filter="*">All</li>
                            <li data-filter=".acao">Ação</li>
                            <li data-filter=".romance">Romance</li>
                            <li data-filter=".terror">Terror</li>
							<li data-filter=".comedia">Comédia</li>
							<li data-filter=".tensao">Tensão</li>
							<li data-filter=".superacao">Superação</li>
                        </ul>
                    </div>
                </div>
            </div>

			{% if not books %}
			<div class="text-center">
                <h2>Não há livros com esse título.</h2>
                <br>
                <img src="{{ url_for('static', filename= 'img/media/no-books.png') }}" style="max-width:20%;">
                <br><br><br>
                <h3>Busque outros livros!</h3>
            </div>
			{% elif 'error' in books %}
			<div class="text-center">
				<h1>Erro ao buscar livros!</h3>
				<br>
				<img src="{{ url_for('static', filename= 'img/media/no-books.png') }}" style="max-width:20%;">
				<br><br><br>
				<h3>Tente novamente mais tarde!</h3>
			</div>
			
			{% else %}
				<div class="row product-lists">
					{% for book in books %}
					<div class="col-lg-4 col-md-4 text-center">
						<div class="single-product-item">
								<div class="product-image">
									<a href="{{url_for('ecommerce.book', book_id=book.id)}}">
										<img src="{{book.mediumCoverUrl}}">
									</a>
								</div>

			
>>>>>>> backend-joao
							<br>
							<a href="{{url_for('ecommerce.book', book_id=book.id)}}"><h3>{{book.title}}</h3></a>
							<p class="description">Autor{% if book.authors|length > 1 %}es{% endif %}:
                                {% for author in book.authors %}{{ author }}{% if not loop.last %}, {% endif %}{% endfor %}
                            </p>
							<p class="description">Local: {{book.fatecName}}</p>
							<a href="{{url_for('ecommerce.cart')}}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Adicionar ao carrinho</a>
						</div>
					</div>
					{% endfor %}
				</div>
				{% endif %}
				<!-- 
					<div class="row">
						<div class="col-lg-12 text-center">
							<div class="pagination-wrap">
								<ul>
									<li><a href="#">Prev</a></li>
									<li><a class="active" href="#">1</a></li>
									<li><a href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">Next</a></li>
								</ul>
							</div>
						</div>
					</div>
				-->
		</div>
	</div>
	<!-- end products -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="assets/img/company-logos/1.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/2.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/3.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/4.png" alt="">
						</div>
						<div class="single-logo-item">
							<img src="assets/img/company-logos/5.png" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->
	{% endblock content %}